---
- name: Create EC2
  hosts: localhost
  
  var_files:
    - vars.yml
    - awsauth.yml
  gather_facts: False
  
  tasks:
    - name: Lauch EC2 Instance
      ec2:
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet }}"
        group_id: "{{ groups }}"
        instance_tags: "{{ tags }}"
        wait: True
      register: ec2

    - add_host:
        name: "{{ ec2.instances|selectattr('state', 'equalto', 'running')|map(attribute='ip') }}"
        groups: newEC2instance

    - ec2_win_password:
        instance_id: "{{ ec2.instances|selectattr('state', 'equalto', 'running')|map(attribute='id')|list }}"
        key_file: /etc/ansible/keys/BelronAdmin
        region: "{{ region }}"
