---
- name: Create EC2
  hosts: localhost
  gather_facts: False
  vars:
    keypair: BelronAdmin
    instance_type: t2.micro
    image: ami-dd9eb6ae
    region: eu-west-1
    subnet: subnet-2bc7504f
    groups: 
      - sg-47c62e20
      - sg-fd3ed69a
    tags:
      Name: MKTEST
  tasks:
    - name: Lauch Instance
      ec2:
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet }}"
        group_id: "{{ groups }}"
        instance_tags: "{{ tags }}"
        wait: True
      register: ec2

    - add_host:
        name: "{{ ec2.instances|selectattr('state', 'equalto', 'running')|map(attribute='tags.Name') }}"
        groups: newEC2instance
      with_items: ec2

    - debug:
        msg: " the id is {{ item.instances|selectattr|map(attribute='instance_id')  }}"
      with_items: ec2

    - ec2_win_password:
        instance_id: item.instances.id
        key_file: /etc/ansible/keys/BelronAdmin
        region: "{{ region }}"
      with_items: ec2
